[package]
name = "archana-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true
rayon.workspace = true
walkdir = "2.5.0"

zip = "8.6.0"
tar = "0.4.45"
flate2 = "1.1.9"
bzip2 = "0.6.1"
xz2 = "0.1.7"
zstd = "0.13.3"
sevenz-rust = "0.6.1"

[features]
default = ["zip", "tar", "sevenzip"]
zip = []
tar = []
sevenzip = []
rar = []